array-reduce - Simon Kim.
Skim-329/rc0821-code-solutions pull request #99
Opened 2021-10-15 20:16 UTC by Skim-329

<img width="487" alt="Screen Shot 2021-10-15 at 1 15 01 PM" src="https://user-images.githubusercontent.com/88165545/137548249-38fd2573-693f-444b-b358-6b039fee0b54.png">

2021-10-15 20:22 UTC, TimelikeClosure requested changes

2021-10-15 20:22 UTC, TimelikeClosure commented on array-reduce/main.js
> +console.log(numbers.reduce(product));
`sum` and `product` should be the final sum and product (respectively), not the callback functions.

---

![image](https://user-images.githubusercontent.com/16143771/137548554-2f06cf1d-b630-48d5-b2df-6fd8841be767.png)

2021-10-15 20:22 UTC, TimelikeClosure commented on array-reduce/main.js
> +console.log(composite);
Please try each of these using exactly one `reduce` each, with no `filter`s or `map`s:

---

![image](https://user-images.githubusercontent.com/16143771/137548766-12a6ffd9-8d90-4fed-8d10-f9ee5a7629a7.png)

2021-10-16 22:02 UTC, Skim-329 commented
<img width="820" alt="Screen Shot 2021-10-16 at 3 00 27 PM" src="https://user-images.githubusercontent.com/88165545/137603104-dfb2f54c-fdef-49f9-9482-6a12971553ef.png">

2021-10-18 17:16 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-10-18 17:17 UTC, merged